In [1]:
import pandas as pd #  pandas
import seaborn as sns # seaborn
import matplotlib.pyplot as plt # matplotlib.pyplot
from pprint import pprint
from ucimlrepo import fetch_ucirepo # se importa fetch_ucilrepo

# Se carga el dataset DARWIN
darwin = fetch_ucirepo(id=732)
# X (features)
x = darwin.data.features

# Y (targets)
y = darwin.data.targets

# Se concatena features y target en un mismo dataframe 'df'
df = pd.concat([x,y], axis=1)

# Exploración inicial TAREA 1

Transformamos el dataset para que contenga solo las 18 primeras columnas y asi trabajar con las características propias de la tarea 1; se incluye la última columna 452 que cuenta con la clase

In [6]:
# df1 con cols 1:19 (hasta 18)
cols_selec = df.columns[1:19]
cols_selec = list(cols_selec) + [df.columns[451]] # + col 452

df1 = df[cols_selec]

# Se revisa que las dimensiones del nuevo dataset sean las correctas
df1.shape

(174, 19)

Nombre de las columnas que se incluyen dentro de la tarea q1 (abarca las 18 primeras columnas)

In [10]:
# Nombres 0:18 cols
print(df1.columns)

Index(['air_time1', 'disp_index1', 'gmrt_in_air1', 'gmrt_on_paper1',
       'max_x_extension1', 'max_y_extension1', 'mean_acc_in_air1',
       'mean_acc_on_paper1', 'mean_gmrt1', 'mean_jerk_in_air1',
       'mean_jerk_on_paper1', 'mean_speed_in_air1', 'mean_speed_on_paper1',
       'num_of_pendown1', 'paper_time1', 'pressure_mean1', 'pressure_var1',
       'total_time1', 'class'],
      dtype='object')

Estadistica descriptiva de las primeras 18 columnas

In [13]:
df1.describe()

,air_time1,disp_index1,gmrt_in_air1,gmrt_on_paper1,max_x_extension1,max_y_extension1,mean_acc_in_air1,mean_acc_on_paper1,mean_gmrt1,mean_jerk_in_air1,mean_jerk_on_paper1,mean_speed_in_air1,mean_speed_on_paper1,num_of_pendown1,paper_time1,pressure_mean1,pressure_var1,total_time1
count,174.000000,174.000000,174.000000,174.000000,174.000000,174.000000,174.000000,174.000000,174.000000,174.000000,174.000000,174.000000,174.000000,174.000000,174.000000,174.000000,174.000000,174.000000
mean,5664.166667,0.000010,297.666685,200.504413,1977.965517,7323.896552,0.416374,0.179823,249.085549,0.067556,0.020510,4.108963,3.801431,8.862069,5800.373563,1678.352702,131024.428347,11464.540230
std,12653.772746,0.000003,183.943181,111.629546,1648.306365,2188.290512,0.381837,0.064693,132.698462,0.074776,0.004496,2.423514,2.235803,5.779518,4479.077663,278.743558,62642.298685,15702.313687
min,65.000000,0.000002,28.734515,29.935835,754.000000,561.000000,0.067748,0.096631,41.199445,0.011861,0.012617,0.447541,0.502808,1.000000,805.000000,642.634761,21620.134230,2490.000000
25%,1697.500000,0.000008,174.153023,136.524742,1362.500000,6124.000000,0.218209,0.146647,161.136182,0.029523,0.017977,2.645708,2.494200,5.000000,3982.500000,1535.729836,89115.565730,5718.750000
50%,2890.000000,0.000009,255.791452,176.494494,1681.000000,6975.500000,0.275184,0.163659,224.445268,0.039233,0.019561,3.620897,3.252146,8.000000,4905.000000,1745.288431,128550.962450,8397.500000
75%,4931.250000,0.000011,358.917885,234.052560,2082.750000,8298.500000,0.442706,0.188879,294.392298,0.071057,0.021536,4.732546,4.397121,11.000000,6286.250000,1887.945491,166586.304500,11250.000000
max,109965.000000,0.000028,1168.328276,865.210522,18602.000000,15783.000000,2.772566,0.627350,836.784702,0.543199,0.043455,15.533955,18.187079,54.000000,46120.000000,2019.427986,549505.005400,156085.000000

Con estos datos se pueedn observar la media, desviación, cuartiles, valores máximo y mínimo para las variables de la tarea 1.

A continuación, se estudian los valores medios en las distintas variables para los pacientes con AD (P) y sanos (H).

In [17]:
df1.groupby('class').mean(numeric_only=True)

,air_time1,disp_index1,gmrt_in_air1,gmrt_on_paper1,max_x_extension1,max_y_extension1,mean_acc_in_air1,mean_acc_on_paper1,mean_gmrt1,mean_jerk_in_air1,mean_jerk_on_paper1,mean_speed_in_air1,mean_speed_on_paper1,num_of_pendown1,paper_time1,pressure_mean1,pressure_var1,total_time1
class,,,,,,,,,,,,,,,,,,
H,4781.647059,0.000009,340.818502,222.853289,2075.976471,7312.894118,0.470852,0.184009,281.835895,0.077201,0.020630,4.648898,4.259800,7.823529,4604.941176,1765.820217,127679.696701,9386.588235
P,6507.022472,0.000010,256.454275,179.159981,1884.359551,7334.404494,0.364344,0.175825,217.807128,0.058344,0.020396,3.593294,3.363663,9.853933,6942.078652,1594.816311,134218.834975,13449.101124